Add support for custom migration paths and nable names in Migration Archiving Tasks
umbrellio/umbrellio-sequel-plugins pull request #40
Opened 2024-09-11 09:17 UTC by lireirelico

2024-09-12 11:06 UTC, tycooon approved these changes

2024-09-12 11:07 UTC, tycooon commented
Го версию сразу бампнем?)

2024-09-12 13:09 UTC, loadkpi requested changes
давай добавим немного ридми, как этим пользоваться

2024-09-13 15:37 UTC, tycooon commented
Я выпилил чейнжлог в пользу гитхаб релизов, нужно мастер освежить)

2024-09-16 13:59 UTC, loadkpi approved these changes

2024-09-18 07:35 UTC, loadkpi requested changes

2024-09-20 13:50 UTC, loadkpi approved these changes

2024-09-23 07:21 UTC, merged